In [ ]:
-- 1-1
-- Insert into the dbo.Customers table a row with:
-- custid:  100
-- companyname: Coho Winery
-- country:     USA
-- region:      WA
-- city:        Redmond
Use WideWorldImporters
DROP TABLE IF EXISTS dbo.Customers;
CREATE TABLE dbo.Customers (
    CustomerID varchar(100),
    CompanyName varchar(100),
    country varchar(100),
    region varchar(100),
    city varchar(100)
);

INSERT INTO dbo.Customers (CustomerID, CompanyName, country, region, city)
VALUES ('100', 'Coho Winery', 'USA', 'WA', 'Redmond');

SELECT *
FROM dbo.Customers
WHERE CustomerID = '100';

-- 1-2
-- Insert into the dbo.Customers table 
-- all customers from Sales.Customers
-- who placed orders

Insert into dbo.Customers 
SELECT CustomerID, CustomerName,[PostalPostalCode], [PostalCityID], [PostalAddressLine1]
FROM Sales.Customers AS C
WHERE [BuyingGroupID] Is not null

Select *
from Sales.Customers

-- 1-3
-- Use a SELECT INTO statement to create and populate the dbo.Orders table
-- with orders from the Sales.Orders
-- that were placed in the years 2014 through 2016

DROP TABLE IF EXISTS dbo.Orders
SELECT *
INTO dbo.Orders
FROM Sales.Orders
WHERE orderdate >= '20140101'
AND orderdate < '20170101'

/* -- 2
-- Delete from the dbo.Orders table
-- orders that were placed before August 2014
-- Use the OUTPUT clause to return the orderid and orderdate
-- of the deleted orders
 
-- Desired output:
orderid     orderdate
----------- -----------
10248       2014-07-04 
10249       2014-07-05 
10250       2014-07-08 
10251       2014-07-08 
10252       2014-07-09 
10253       2014-07-10 
10254       2014-07-11 
...
...
...
*/

DELETE FROM dbo.Orders
OUTPUT deleted.orderid, deleted.orderdate
WHERE orderdate < '20140801'


-- 3
--- Delete from the dbo.Orders table orders placed by customers from Brazil


DELETE FROM dbo.Orders
WHERE EXISTS
(SELECT *
FROM dbo.Customers AS C
WHERE Orders.CustomerID = C.CustomerID
AND C.country = 'Brazil')

Select*
from Sales.Customers

-- Proposition 4: Increase the Credit Limit of a Customer
Select CreditLimit
From Sales.Customers
UPDATE Sales.Customers
SET CreditLimit = CreditLimit + 1000
WHERE CustomerID = 500;

-- Proposition 5: Update the Delivery Method for a Customer

UPDATE Sales.Customers
SET DeliveryMethodID = 4
WHERE CustomerID = 9;

Select CustomerID, DeliveryMethodID
from Sales.Customers

-- Proposition 6: Taking off fax numbers entirely. 

UPDATE Sales.Customers
SET FaxNumber = NULL;
-- &&
ALTER TABLE Sales.Customers
DROP COLUMN FaxNumber;

Select *
From Sales.Customers

-- Proposition 7: Increase Standard Discount for All Customers in a Specific City
Select *
From Sales.Customers

UPDATE Sales.Customers
SET StandardDiscountPercentage = StandardDiscountPercentage + 5
WHERE DeliveryCityID < 1000

--Proposition 8: Update the Phone Number Format for All Customers

Select CustomerID, [PhoneNumber]
From Sales.Customers

UPDATE Sales.Customers
SET PhoneNumber = REPLACE (PhoneNumber, ' - ', ' ');

-- Propositon 9: Update the Credit Limit for Customers 
-- in a Specific City with High Standard Discount

UPDATE C
SET C.CreditLimit = C.CreditLimit + 500
FROM Sales.Customers as C 
INNER JOIN Application.Cities as Ci ON C.PostalCityID = Ci.CityID
WHERE Ci.CityName = 'New York'
  AND C.StandardDiscountPercentage >= 10;